### PR TITLE
Graph Filtering

### PR DESCRIPTION
**Pull request by ajbowler**
**Changes:**
- Filtering:
  - Can filter nodes based on numerical comparisons of a property, such as >, <, or =
  - Can filter nodes based on whether or not they have a certain property at all
  - Nodes that are filtered out are grayed out and slightly transparent, while remained nodes are highlighted red
  - Added a button group for filtering, and clearing any active filters. Clearing filters returns the graph to its normal state
  - Huge props to @mcsgroi for coming up with the filtering concepts and initial logic
- Minor UI improvements:
  - The Node Properties Panel returns to an empty state after a node is deselected

**Filtering nodes without a property:**
image

**Filtering nodes less than - greater than works the same way:**
image

**Equals (this is actually a good alternative for searching for something too):**
image

### CODE REVIEW

**Comment by mcsgroi** [comment]
+1 Looks good Andrew, nice work!

**Comment by cheese-stands-alone** [comment]
+1

**Comment by algmzestrd** [comment]
+1

**Comment by winder487** [comment]
Excellent work, my friend. +1

**Pull request merged**
