### PR TITLE
Node Searching

### PR DESCRIPTION
**Pull request by ajbowler**
Wasn't a current sprint item, but it was an easy requirement to get out of the way, and will greatly benefit our upcoming demo.

**Changes:**
- Added the ability to search for nodes by property/value. There are two input boxes, one is the property to search for within the nodes. If no property is entered, it defaults to searching by ID. The second box is the search value.

[Video Demonstration](http://www.youtube.com/watch?v=JRYCwPoh0qc)

### CODE REVIEW

**Comment by algomez** [comment]
+1

**Comment by winder487** [comment]
Looks pretty good. +1

**Comment by cheese-stands-alone** [comment]
+1

**Comment by mcsgroi** [comment]
+1

**Pull request merged**
