### PR TITLE
Echo request in the response message

### PR DESCRIPTION
**Pull request by ajbowler**
When the client sends a request to the server over WebSocket, it sends a request parameter telling the server what it's asking for. I think the server should send the request parameter back in the `message` parameter in the response. This allows the client to easily handle the payload by checking what's in the message.

@rwhite226 I can't test this, so let me know if any additional changes need to be made in the Python code for this to work.

### CODE REVIEW

**Comment by algomez** [comment]
+1

**Comment by ajbowler** [comment]
capture

@rwhite226 Would you be able to implement this on the `handler-messages` branch in the next day or two? I'm not sure how to do it.

**Comment by cheese-stands-alone** [comment]
Added that stuff

**Comment by ajbowler** [comment]
I need to test this stuff this evening, I'll just try pinging the messages with the client and if everything's in order we should be good.

**Comment by ajbowler** [comment]
lol

**Comment by ajbowler** [comment]
I tested it with other client requests and it looks good :+1: 

@algmzestrd @mcsgroi @winder487 look good?

**Comment by winder487** [comment]
Looks good to me. Sorry to hear you bros struggling with it. ^-^'

**Pull request merged**
