### PR TITLE
Fixed REST upload error

### PR DESCRIPTION
**Pull request by mcsgroi**

### CODE REVIEW

**Comment by ajbowler** [comment]
:+1:

**Comment by ajbowler** [comment]
You'll want to resolve those merge conflicts by merging master in here and using your changes over master's. @rwhite226 commented out some of the file handling lines cause they were still broken when we were working on the handler messages.

**Comment by ajbowler** [comment]
:+1:

**Comment by winder487** [comment]
+1

**Comment by algmzestrd** [comment]
+1

**Comment by cheese-stands-alone** [comment]
+1

**Pull request merged**
