### PR TITLE
Reconfigure WebSocket server, remove bundle.js from gitignore

### PR DESCRIPTION
**Pull request by ajbowler**
We're working on a local server now so we need to update the WebSocket server to run on localhost, and port 80 is the only one we have open for HTTP and WebSockets.

I cannot test this locally right now because Windows gets mad at `package.sh` for me even with Cygwin when it tries to run the `zip` command, and the VPN for Iowa State network isn't working for me for whatever reason so I can't SSH into the actual server. I'm not in Ames until tomorrow afternoon. Perhaps @rwhite226 or @agomez-dev can give this a shot?

Also, I don't know if this is all we need to update to make this work, so please give advice if we need to do more.

Just trying to get this moving as fast as possible.

### CODE REVIEW

**Comment by algomez** [comment]
+1. You should just merge this in. It's not big enough to need the whole team looking at it.

**Comment by ajbowler** [comment]
I agree, the only thing I need to know beforehand is if this is all we need
to reconfigure, because I don't know for sure.

**Comment by algomez** [comment]
I'll pull down the branch and check it out.

**Comment by algomez** [comment]
Seems like it allows access to the server. I can connect to it through the IP Address on Port 80. There's still some more setup to be done, but this was the right first step.

screen shot 2016-03-19 at 12 34 41 pm

**Comment by ajbowler** [comment]
Ahhh, excellent! Thanks very much for checking that, I'm unable to access
the VPN from my hometown for whatever reason. I'll get this merged

**Pull request merged**
