### PR TITLE
Jasmine integration

### PR DESCRIPTION
**Pull request by algmzestrd**
I failed at squashing the commits. My bad. Tests are not at all done, but I wanted you all to check this out and become familiar with Jasmine.

### CODE REVIEW

**Comment by ajbowler** [comment]
This is a good start, and I found a great example [here](http://www.toptal.com/react/how-react-components-make-ui-testing-easy). Source code [here](https://github.com/Swizec/react-testing-example). What's nice about this example is that it's a scatter plot, so it's not far from the mark for what we're trying to do with Graphalyzer.

We will need a test runner of some sort, and this example uses Karma as a test runner, Mocha as the framework, and Webpack for module loading. We can use this as a guideline and use Jasmine instead of Mocha if we want.

**Comment by ajbowler** [comment]
As far as merging this branch goes, it may be best to write all of the tests on here before finally merging it. We'll want to remove that example code before merging it into master.

**Comment by algmzestrd** [comment]
You had mentioned Selenium before and, while it alone will not do everything we want, it can be used to emulate the browser and automate the tests. I don't know about the other ones you mentioned. I'll check them out when I have time.

**Comment by ajbowler** [comment]
Closed due to #20. I'll delete the old branch as well.

**Pull request closed without merging**
