### PR TITLE
Search Panel Dropdown, WebSocket client-side improvements

### PR DESCRIPTION
**Pull request by ajbowler**
**Changes:**
- Search Panel now has a dropdown with a list of graphs stored on the server.
  - Click the refresh button to update the list, in case of file changes
- The WebSocket connection process is much more stable. The application now waits until the connection is established before attempting to send messages, and an error is displayed to the user when there is an error with the connection.
- Various code cleanups

**Dropdown menu:**
image

**Connection error alert:**
image

### CODE REVIEW

**Comment by ajbowler** [comment]
This will wait until #16  and the as of now unsubmitted PR from @rwhite226 are merged.

**Comment by ajbowler** [comment]
@rwhite226 thinks it's good to go, shouldn't be affected by the backend work he's doing.

@mcsgroi 
@algmzestrd 
@winder487 
Look good?

**Comment by winder487** [comment]
Yup. I've already perused this one. +1

**Comment by algmzestrd** [comment]
+1. Looks good to me.

**Comment by cheese-stands-alone** [comment]
+1

**Pull request merged**
