### PR TITLE
Search Panel, WebSocket service for the client

### PR DESCRIPTION
**Pull request by ajbowler**
Implementation of basic search panel that can send a graph search query to the server.

**Changes:**
- `search-panel.html`, `search-panel.js`
  - Search Panel component for a user to search for a graph through WebSocket connection to the server
    - Alerts user when a graph name is not provided
    - Node name and degrees parameters are available, but not yet functional, as they are not key to the end of the current sprint.
- WebSocket service is instantiated when the client loads, available for use by any other component.
- Added some more CSS to the page

capture

### CODE REVIEW

**Comment by ajbowler** [comment]
@rwhite226 Any idea why this build is failing? It must be within the D code somewhere, since Travis isn't configured to deal with the UI code. It did this when I merged a small README update earlier today, so I'm guessing this isn't significant? Or are there some errors in the D code that are on the master branch, cause this branch hasn't changed any server code.

**Comment by ajbowler** [comment]
Hoping to get this merged today, so we can finish the other components before Friday.

@rwhite226 
@Penguinparty 
@algmzestrd 
@winder487

**Comment by cheese-stands-alone** [comment]
I know why it's failing. The new versions of dmd and vibe (which where released today) are more strict about something. I was testing it earlier and have a fix in my branch. You can ignore it for the time being. Besides that it looks good.

**Comment by ajbowler** [comment]
@rwhite226 That's what I figured. Is it possible to keep dependency versions for our environment constant throughout development, so we're not refactoring our code whenever someone pushes an update out?

**Comment by cheese-stands-alone** [comment]
We can, though I though it would be better to build against the newest versions. For example we have this issue because I was essentially relying on a bug for the project to build. If left untouched/unseen issues like this can damage the design of a project and require major changes if other things depend on the bug.  Plus there are things in the new version that benefit our project.

**Comment by ajbowler** [comment]
@rwhite226 it's your call, that makes sense to me.

**Comment by mcsgroi** [comment]
Looks good Andrew

**Comment by winder487** [comment]
Looks pretty good to me. I'd be more comfortable if the Travis build wasn't failing, but it seems like it doesn't mean all that much.

**Comment by ajbowler** [comment]
It'll get fixed when @rwhite226 finishes up his current branch. I agree that it's something that we should keep from breaking in the future. I'll merge this.

**Pull request merged**
