### PR TITLE
Added REST file upload functionality

### PR DESCRIPTION
**Pull request by mcsgroi**

### CODE REVIEW

**Comment by ajbowler** [comment]
This has conflicts, is this branch up to date with master?

**Comment by mcsgroi** [comment]
No I'll need to update it. Noticed right after I initiated the pull request

**Comment by mcsgroi** [comment]
Resolved merge conflicts

**Comment by ajbowler** [comment]
Would usage of Flask need to be noted in the design document?

Otherwise,

**Comment by algmzestrd** [comment]
I would say yes.

**Comment by mcsgroi** [comment]
Ya, probably

**Comment by agomez-dev** [comment]
Stupid question. You made it so that the upload directories are customizable?

**Comment by algmzestrd** [comment]
Stupid question. You made it so that the upload directories are customizable?

**Comment by mcsgroi** [comment]
Ya, if you look at the initRestUpload file the variable tempDirectory is passed into the configuration parameters for flask and accessed when a file is uploaded.

**Comment by algmzestrd** [comment]
That's what I thought. +1

**Comment by winder487** [comment]
Flask is neat-o. +1

**Comment by cheese-stands-alone** [comment]
Looks good to me.

**Pull request merged**
