### PR TITLE
UI - Simpler Graphics

### PR DESCRIPTION
**Pull request by ajbowler**
**Changes:**
- Made the nodes solid colors without borders unless selected. Slightly faster drawing time!
- Disabled smooth edges. They now draw in rigid straight lines. This made drawing MUCH faster.
- Made app scale for widescreen displays

image

### CODE REVIEW

**Comment by cheese-stands-alone** [comment]
Hijacked you RP a little since I had a few similar changes. 
Added css to make the app scale to widescreen.
Explicitly disabled physics, because if you moved an node before it would enable physics.

**Comment by ajbowler** [comment]
@rwhite226 disabling the physics engine entirely makes sense when you only intend on drawing the graph once, but previously when I tested drawing the graph each time a chunk was loaded, everything overlapped each other when physics was disabled, because physics enables the repulsion fields for the nodes, keeping everything from overlapping.

I think we need to make a decision on whether we draw the graph only once, or draw it each time a chunk is loaded.

When were you able to move nodes? In the options I have `dragNodes: false` specified, so they can't be moved. The only thing you can move is the canvas "camera" like zooming or panning around.

**Comment by ajbowler** [comment]
Had some discussion with @rwhite226 and @mcsgroi this afternoon and we're good to go. Once everyone takes a look it should be good to merge.

**Comment by winder487** [comment]
+1

**Comment by algomez** [comment]
+1

**Comment by mcsgroi** [comment]
+1

**Comment by cheese-stands-alone** [comment]
+1

**Pull request merged**
