### PR TITLE
Frontend logging

### PR DESCRIPTION
**Pull request by ajbowler**
**Changes:**
- Added a logger prop for frontend components
- Logger prints out timestamped messages for various tasks
  - Data requests and responses from the server, such as requesting a graph or list of graphs
  - Start and end times for drawing a graph
- Added changes to the Vis options. Graph draws **much** faster now.

image

### CODE REVIEW

**Comment by algmzestrd** [comment]
+1. Woah.

**Comment by winder487** [comment]
Looks good to me. +1

**Comment by mcsgroi** [comment]
+1

**Comment by cheese-stands-alone** [comment]
+1

**Pull request merged**
