### PR TITLE
Jest setup

### PR DESCRIPTION
**Pull request by algmzestrd**
Sorry about the duplicate commits. This should ensure that all of us can write tests.

### CODE REVIEW

**Comment by ajbowler** [comment]
I think something nasty happened on the branch cause it pulled one of @rwhite226 's commits in it, maybe a botched rebase or something, but otherwise all the code looks solid.

+1

**Comment by ajbowler** [comment]
@rwhite226 
@mcsgroi 
@winder487 

You guys good?

**Comment by winder487** [comment]
@ajbowler Yuuup, just a bit slow getting to the pull request. +1

**Comment by cheese-stands-alone** [comment]
+1

**Comment by mcsgroi** [comment]
Ya sorry, looks good sir

**Pull request merged**
