### PR TITLE
Simple Graph Panel

### PR DESCRIPTION
**Pull request by ajbowler**
Changes:
- Added a `GraphController` to `app.js`. This uses the Vis.js library to display the graph. 
  - Currently, this graph is hardcoded data, which will be replaced by the **GraphDataHandler** (see Design Document) in a later PR, but for demonstration purposes this works.
- Added `angular-vis.js` to the project repo. This is [Vis.js's](http://visjs.org) official Angular package, that unfortunately, they don't have published to npm, as it is still fairly new. So this file is on our project repo temporarily, despite not being our code. 
  - One thing that we will need (in a separate PR) is a build tool that runs `npm install` for the npm packages, then to download the `angular-vis.js` file separately into the file system. This can be done later.
- Added some basic panel CSS for clarity on where everything else on the page. This will obviously be made to actually look nice later when we get things integrated.

capture

### CODE REVIEW

**Comment by ajbowler** [comment]
Also, FYI to @algmzestrd particularly, next on my plate is the **GraphDataHandler**, in case you're looking for frontend things to work on.

**Comment by cheese-stands-alone** [comment]
Looks good to me. The only thing I can think to add is that we might want to have a standard code format (i.e. some of your files end in a nl and other don't.) For the backend I have been using dfmt, the frontend could use something like [this](https://github.com/beautify-web/js-beautify). But this is mostly cosmetic.

**Comment by ajbowler** [comment]
@rwhite226 Yes, code style was something in the back of my head as well. For previous JavaScript projects I've worked on I've followed the [Google Style Guide](https://google.github.io/styleguide/javascriptguide.xml). Since I'm working with Angular, though, I wasn't sure what standard to follow. @algmzestrd might have more thoughts. I think for Demo 1, this isn't as important, though.

**Comment by ajbowler** [comment]
Added a screenshot of what I've done.

**Comment by ajbowler** [comment]
Pushed up some code formatting changes. I'd prefer to get this merged tonight before the client meeting tomorrow and so @algmzestrd can work on his stuff with the updated codebase. Anything else here you guys can think of?

@rwhite226 
@Penguinparty 
@winder487

**Comment by mcsgroi** [comment]
Nope looks good @ajbowler

**Comment by winder487** [comment]
:+1: Perhaps some comments denoting authorship and modifications at the top of the documents could be in order?

**Comment by ajbowler** [comment]
Done. Just need @algmzestrd to take a look at it. If he has any suggestions, either he or I can add them, then this should be good to merge.

**Comment by algmzestrd** [comment]
All good. +1.

**Pull request merged**
